spring:
  datasource:
    url: jdbc:mysql://47.92.72.146:3306/mall?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  cache:
    type: ehcache
    ehcache:
      config: classpath:/ehcache.xml
  profiles:
    active: prod
  druglots:
      contextPath: http://mall.druglots.cn
      cookieDomain: druglots.cn
server:
  port: 8082
  servlet:
    context-path: /mall
mybatis-plus:
  mapper-locations: classpath*:/mappers/**/*.xml
  type-aliases-package: cn.druglots.mall.**.entity


#---
#spring:
#  profiles: prod
#  datasource:
#    url: jdbc:mysql://localhost:3306/wemall?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
#    username: root
#    password: temii
#---
#spring:
#  profiles: dev
#  datasource:
#    url: jdbc:mysql://47.92.72.146:3306/mall?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
#    username: root
#    password: 123456