spring:
  datasource:
    url: jdbc:mysql://47.92.72.146:3306/cloud-mall?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password:
server:
  port: 9100
  servlet:
    context-path: /cloud-mall
debug: true
mybatis-plus:
  mapper-locations: classpath*:/mappers/**/*.xml
  type-aliases-package: cn.druglots.mall.**.entity
  global-config:
    db-config:
      insert-strategy: ignored
      update-strategy: not_empty
  check-config-location: true
  executor-type: simple
